config/routes.rb
Rails.application.routes.draw do
  # Changes url/users/sign_in to url/sign_in
  devise_for :user, :path => "/", path_names: { 
    sign_in: 'login', 
    sign_out: 'logout',
    sign_up: 'sign_up' 
  }

  resources :staffs
  resources :customers
  resources :days

  authenticated :user do 
    root 'logged_in#user_log_in', as: :authenticated_root, via: :get
  end

  unauthenticated :user do
    root 'static_pages#welcome_page'
  end

  match "/staff/:page",        to: 'staffs#next_page',        via: [:get]
  match "/customers/:page",    to: 'customers#next_page',     via: [:get]
  #get '/staff/new_staff/' => 'staffs#new_staff', as: :reassign_staff

end

app/controllers/logged_in_controller.rb
class LoggedInController < ApplicationController
	def user_log_in
		@staffs = current_user.staffs.pagination(0,5)
		@customers = current_user.customers.pagination(0,5)
	end
end

app/helpers/logged_in_helper.rb
module LoggedInHelper
  def user_log_in
  end
end

app/views/logged_in/user_log_in.html.erb
	<!-- CENTRAL PANEL -->
	<div class="col-md-8 central-panel">
		<!-- STAFF -->
		<div class="row">
			<div class="col-md-5 col-md-offset-1 logged-margin-top">
				<h1><%= link_to "Staff", staffs_path %></h1>
				<small>page number: </small>
			</div>
		</div>
		<div class="row">
			<!-- Dummy col -->
			<div class="col-md-1 staff-styling arrow" id="prev">
				&lArr;
			</div>
			
			<div id="staff-member-display">
				<% @staffs.each do |t| %>

				<div class="col-md-2 staff-styling">
					<%= link_to staff_path(t) do%>
					<div class="well">
						Name: <%= t.name %> <br>
						Happiness: <%= t.happiness %> <br>
						Salary: <%= t.salary %> <br>
						Performance: <%= t.performance %> <br>
						
					</div>
					<% end %>
				</div>
				<% end %>
			</div>
			
			
			<div class="col-md-1 staff-styling arrow" id="next">
				&rArr;
			</div>
			
		</div>
		
		<!-- CUSTOMER PART -->
		<div class="row">
			<div class="col-md-5 col-md-offset-1 logged-margin-top">
				<h1><%= link_to "Customers", customers_path %></h1>
				<small>page number: </small>
			</div>
		</div>
		<div class="row">
			<!-- Dummy col -->
			<div class="col-md-1 staff-styling arrow" id="prev-cust">
				&lArr;
			</div>
			
			<div id="customer-member-display">
				<% @customers.each do |t| %>

				<div class="col-md-2 staff-styling">
					<%= link_to customer_path(t) do%>
					<div class="well">
						Name: <%= t.name %> <br>
						Affluence: <%= t.affluence %> <br>
						Handled by: <%= t.staff.name %> <br>
					</div>
					<% end %>

				</div>
				<% end %>
			</div>
			
			
			<div class="col-md-1 staff-styling arrow" id="next-cust">
				&rArr;
			</div>
			
		</div> <!-- END OF CUSTOMER -->
	</div> <!--  END-->
	